### ISSUE TITLE
I'm getting ERROR IN CALL TO FUNCTION

### ISSUE THREAD

**Issue by vedatyrt** [opengeospatial/teamengine#124] opened 2015-09-09 13:43 UTC
Fatal Error: Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.net.UnknownHostException: C; SystemID: file:/C:/Users/vedat.yurt/teamengine/teamengine-web/target/te-base/work/src_main_scripts_ctl_main.xml/csw$Main.test; Line#: 40; Column#: -1
Eyl 09, 2015 4:35:47 PM com.occamlab.te.TECore executeTest
SEVERE: Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.net.UnknownHostException: C
Test csw:Main Failed
Report file "C:\Users\vedat.yurt\teamengine\teamengine-web\target\te-base\users\vedat.yurt\2702fdbb-291b-4713-a2f5-2c1c6a5994ec\report.html" created!
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.242 sec <<< FAILURE! - in com.occamlab.te.web.VerifyTestSuite
executeStartingTest(com.occamlab.te.web.VerifyTestSuite)  Time elapsed: 7.242 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected result. expected:<5> but was:<6>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at com.occamlab.te.web.VerifyTestSuite.executeStartingTest(VerifyTestSuite.java:144)

Results :

Failed tests:
  VerifyTestSuite.executeStartingTest:144 Unexpected result. expected:<5> but was:<6>

Tests run: 10, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] TEAM Engine ........................................ SUCCESS [  2.517 s]
[INFO] TEAM Engine - Tomcat Realm ......................... SUCCESS [  5.865 s]
[INFO] TEAM Engine - Shared Resources ..................... SUCCESS [  7.317 s]
[INFO] TEAM Engine - Core Module .......................... SUCCESS [ 26.962 s]
[INFO] TEAM Engine - Service Providers .................... SUCCESS [  8.307 s]
[INFO] TEAM Engine - Web Application ...................... FAILURE [ 30.387 s]
[INFO] TEAM Engine - Console Application .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2015-09-09T16:35:47+03:00
[INFO] Final Memory: 39M/429M

**Comment by bermud** [comment] 2015-09-09 14:35
master and 4.2 build OK with 'mvn clean install'. What branch are you trying to build?

**Comment by vedatyrt** [comment] 2015-09-10 07:00
In windows, I got this error. Then I tried it on Ubuntu and it works.

**Comment by upendra-sachan** [comment] 2015-09-10 13:22
Hi vedatyrt,

This issue occur inside CSW test, which we used to create JUnit test.
Can you send me your
"file:/C:/Users/vedat.yurt/teamengine/teamengine-web/target/te-base/work/src_main_scripts_ctl_main.xml/csw$Main.test"
file. By this it is easy to me what is the cause behind it.

Thanks.


------
Upendra Sachan
Mindstix Software Labs
http://www.mindstix.com

*Email:* upendra.sachan@mindstix.com <blah@mindstix.com>
*Phone:* +91 8446253174
*Skype:* upendra.sachan1

**Comment by agtokty** [comment] 2015-09-13 19:12
Hi all,
I also try to install  "master" branch in windows 10, i got same errors.
My system properties: Win 10, 64 bit, English Language,

* Here is installation log :  https://gist.github.com/agtokty/04421151cc118c060b37
* this is index.xml under    C:\Users\agit\teamengine\work\src_test_resources_ctl_nested-failure.xml : https://gist.github.com/agtokty/ca6bb7af67d382dfa58a

**Comment by upendra-sachan** [comment] 2015-09-14 09:18
Resolved in https://github.com/opengeospatial/teamengine/commit/dda9cd275b30ca7106bdfb031ab0bf621dfd18cf

**Closed by upendra-sachan** 2015-09-14 09:18 UTC
