### ISSUE TITLE
Delete Session leads to DocumentBuilderFactoryImpl not found

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/teamengine#498] opened 2022-02-21 09:14 UTC
**Describe the bug**
Clicking on Delete Session leads to org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found

**To Reproduce**
1. Run a session
2. Click the Delete Session button
3. The org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found Exception appears

**Expected behavior**
No exception error should result from attempting to Delete a session

**Screenshots**

![Screenshot 2022-02-21 at 09 10 56](https://user-images.githubusercontent.com/18121038/154924372-68643e4c-1462-4e57-8d95-8afac0bb5e7f.png)

**Comment by dstenger** [comment] 2022-02-24 09:36
Problem might be related to the update of xercesImpl-2.12.0.jar to xercesImpl-2.12.2.jar.

**Comment by dstenger** [comment] 2022-03-01 20:35
The error is still occurring on http://cite.ogc.org/te2/ when validating https://maps.ecere.com/ogcapi with OGC API Features test suite.
`HTTP Status 500 - javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found`

**Comment by dstenger** [comment] 2022-03-01 20:37
The error is still occurring on http://cite.ogc.org/te2/ when validating https://maps.ecere.com/ogcapi with OGC API Features test suite.
`HTTP Status 500 - javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found`

**Comment by dstenger** [comment] 2022-03-24 13:07
Also, I am not able to reproduce it on Beta anymore (workflow as described in https://github.com/opengeospatial/teamengine/issues/498#issuecomment-1055837266).

**Comment by dstenger** [comment] 2022-03-28 08:56
This issues seems to be fixed by the recent Beta update.

**Closed** 2022-07-05 18:26 UTC
Labels: bug
