### ISSUE TITLE
Replace HTTP links with HTTPS on HTML, JSP and JavaScript pages

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/teamengine#501] opened 2022-02-21 20:50 UTC
**Describe the bug**

Some links from the User Interface are to HTTP addresses. Modern browsers such as the latest Chrome version block any request from a page on HTTPS to a link on HTTP.

**To Reproduce**
1. Log into https://cite.ogc.org/te2
2. Create a test session (e.g. for OGC API - Features) then attempt run the test
3. Nothing happens.
4. Check the Console (Developer Tools on Chrome) and you will see the error reporting that the request was blocked.

Note that this issue does not occur if the user logs into http://cite.ogc.org/te2

**Expected behavior**
The test session should just run.

**Screenshots**

![Screenshot 2022-02-21 at 09 55 55](https://user-images.githubusercontent.com/18121038/155024610-63c3eabe-6fae-4b06-b76d-5d85573b3fb9.png)

**Comment by dstenger** [comment] 2022-02-22 09:17
Should be a duplicate of #418.
HTTP should not replaced by HTTPS but TEAM Engine should re-use the used protocol so that it can run via HTTPS and HTTP.

**Comment by ghobona** [comment] 2022-03-17 12:40
Requested a discussion with the OGC Infrastructure Office.

**Comment by dstenger** [comment] 2022-04-07 08:51
Problem is now also occurring with Firefox (99.0 (64-Bit)).

**Comment by dstenger** [comment] 2022-07-07 08:16
Was solved by configuring following in proxy: https://github.com/opengeospatial/teamengine/commit/eb01f3de9b3fc1bb0ddf3cb57e81dbd4b4c65e57

**Closed by dstenger** 2022-07-07 08:16 UTC
Labels: bug
