### ISSUE TITLE
Teamengine: error formatting WFS 2.0 test results 

### ISSUE THREAD

**Issue by jill7072** [opengeospatial/teamengine#387] opened 2019-01-28 22:24 UTC
I am running the team engine tests for WFS 2.0 and I'm finding that the test results are properly formatted for some of my URLs but I'm receiving an error for other URLs. This is reproducible on the 1.26 version as well as the beta site (1.30).
![image](https://user-images.githubusercontent.com/19600343/51870173-b03c5d00-2307-11e9-8161-bba03a5a64a5.png)

When I click to view the old test report I get the following message:

> Test tns:Main type Mandatory default result Passed (s0002)
> 
> Assertion: The test subject satisfies all applicable constraints.
> 
> Form d1e46_1:
>    fid=
>    wfs-uri=https://ogccert.dev.geocloud.com:6443/arcgis/services/cite_wfs_200_T/MapServer/WFSServer?service=WFS&version=2.0.0&request=GetCapabilities
> 
> Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.iso19142.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.RuntimeException: Failed to parse resource located at https://ogccert.dev.geocloud.com:6443/arcgis/services/cite_wfs_200_T/MapServer/WFSServer?service=WFS&version=2.0.0&request=GetCapabilities
> Result: Failed

I have a temporary URL that reproduces the error:
https://ogccert.dev.geocloud.com:6443/arcgis/services/cite_wfs_200_T/MapServer/WFSServer?service=WFS&version=2.0.0&request=GetCapabilities

Thanks!

**Comment by dstenger** [comment] 2019-01-29 11:56
Thank you for reporting the issue.

The posted URL is not reachable. Thus, TEAM Engine cannot use it for testing.

If you use official TEAM Engine [1], the service must be reachable via the web.

Instead, if you want to test an internal service, you must set up TEAM Engine by yourself.
If you are familiar with Docker, you can use our Docker Image simplifying the set up process very much
https://hub.docker.com/r/ogccite/ets-wfs20/

Hint: There is also a WFS 2.0 test suite tracker. This issue fits more into that tracker system.
https://github.com/opengeospatial/ets-wfs20/issues

[1] http://cite.opengeospatial.org/teamengine/

**Comment by jill7072** [comment] 2019-02-02 00:00
@dstenger you are right, sorry! The URL should be reachable now. I can still reproduce the issue. 
https://ogccert.dev.geocloud.com:6443/arcgis/services/cite_wfs_200_T/MapServer/WFSServer?service=WFS&version=2.0.0&request=GetCapabilities

Thanks, I didn't realize there was another place for issues. Should I re-enter this issue in the ets-wfs20 queue?

**Comment by dstenger** [comment] 2019-02-04 08:05
Yes, I would be better if we discuss this in the WFS 2.0 issue tracker.
So, if it is no problem, please open this issue in that tracker as well. Then we can close this one as duplicate.

**Comment by dstenger** [comment] 2019-02-05 09:36
Duplicate of https://github.com/opengeospatial/ets-wfs20/issues/142.

**Closed by dstenger** 2019-02-05 09:36 UTC
Labels: question, status:waiting
