### ISSUE TITLE
Detailed old test report of TestNG test suites is erroneous

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#251] opened 2017-10-10 10:20 UTC
Workflow to reproduce bug:

* Execute ets-wfs20 via Web Browser Interface.
* Result is HTML report. -> Go to bottom of page and navigate to ```See the detailed old test report.```.
* Following content is erroneous:
  1. Navigate to ```View Details``` of ```Test tns:Main```. -> Overview of all tests should be shown but test logging is shown instead.
  1. Link to ```See the detailed test report.``` is missing.

The correct behaviour can be reproduced with production [1] and the erroneous with beta [2].

[1] http://cite.opengeospatial.org/teamengine/
[2] http://cite.opengeospatial.org/te2/

**Comment by keshav-nangare** [comment] 2017-10-13 06:38
We investigated this issue an found commit which is affecting this result.

From this commit above issue is producing: 0d7db9cda49d6fd0961a9cd120ce0d914b0c39a4

But in this commit I didn't change anything related to logging and testng result file.

I have added the one dependency **`commons-io`** in pom.xml of teamengine-spi module. Maybe this dependency is affecting to generate this result.

Currently I trying to remove this dependency and finding alternative dependency for it. I will check, is it works or not after removing this dependency.

Thank you.

**Comment by lgoltz** [comment] 2017-10-18 06:11
The transformation from the test-results to the HTML (based on testng) is triggered in the CTL of the Test-Suite (e.g wfs-suite.ctl) in the template tns:testng-report. The transformation is executed, but the template does not match. The problem is that the xml to transform is the rdf/earl document, not the expected testng-result. The log in the console is also corrupt as it is not transformed for the same reasons.

The changes on com.occamlab.te.spi.executors.testng.TestNGExecutor#getPreferredMediaType() from the commit above leads to this behaviour as the default media type is now "application/rdf+xml" and not "application/xml". For the execution with the Web GUI the old behaviour should be restored.

**Comment by lgoltz** [comment] 2017-10-19 07:51
PR #253 includes PR #254 which should be verified and merged first.

**Closed** 2017-10-25 10:52 UTC
Labels: bug, priority:high, status:to-verify

**Comment by dstenger** [comment] 2017-10-25 12:13
**Testing was successful:**

Internal SoapUI test run successfully.

Internal Selenium tests confirm that fix solves the reported problem.

All tests will be made available soon: https://github.com/opengeospatial/teamengine/wiki/Tests-for-TEAM-Engine
