### ISSUE TITLE
Change login time interval

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#364] opened 2018-10-16 17:04 UTC
When failing to provide a correct password, Im getting a message related to login time  interval which is not friendly.

![image](https://user-images.githubusercontent.com/3738898/47033824-c69d1f00-d143-11e8-8002-3aeecaeaf0b1.png)

**Comment by dstenger** [comment] 2018-10-17 08:41
@bermud I cannot reproduce this behaviour on beta environment. Can you please specify the steps which must be executed to reproduce this behaviour?

@keshav-nangare Can you please also check if you are able to reproduce this behaviour?

**Comment by keshav-nangare** [comment] 2018-10-19 10:16
@dstenger 

This issue is related to the connectionTimeout error between the browser and tomcat. Whenever we are on login page and we stay ideal on that page for long time and after that even if we submit the correct username and password this error message will appear. 
The reason is the tomcat expecting a response in a specified time interval[**connectionTimeout**] from the request, after that it will reach to his time limit then it will throw the reported error.

Whenever we open login page the tomcat is sending the JSESSIONID into response with the time interval and if we submit the form after a long time(interval time) then the requested JSESSIONID is invalid.

Following are the steps to reproduce this issue immediately by clearing the cookies:

1. Goto teamengine login page.
2. Right click on page and inspect element.
3. Goto Application tab
4. You can see the cookies with teamengine host URL in left side panel.
5. Right click and clear cookies.
6. Enter username and password and submit. You will get the report error message (408).


Solution: Increase **`connectionTimeout`** time in server.xml of tomcat server.

Reference: 
https://tomcat.apache.org/tomcat-7.0-doc/config/http.html#Standard_Implementation

**Comment by dstenger** [comment] 2018-10-24 08:05
# Conclusion

Behaviour occurs when login page is open for a certain time and session is exceeded.
Thus, the error message is correct and has nothing to do with a correct or incorrect password.

Possible solution:
* Extend connection timeout (but, if this timeout is exceeded, error will occur again).
* Create better error page.

**Comment by keshav-nangare** [comment] 2018-10-29 17:28
> - Create better error page.

I have added new error page and able to redirect if we get 408 status code. Fixed with PR #369 .

**Closed** 2019-04-23 13:23 UTC
Labels: status:to-verify
